# Generated by Django 5.2.16 on 2026-07-23 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaptismRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('officiating_pastor', models.CharField(max_length=255)),
                ('baptism_date', models.DateField()),
                ('place_of_baptism', models.CharField(default='Newlife Main Sanctuary', max_length=255)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Certificate Ready', 'Certificate Ready'), ('Pending Collection', 'Pending Collection'), ('Certificate Collected', 'Certificate Collected')], default='Processing', max_length=30)),
                ('certificate_collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_baptisms', to=settings.AUTH_USER_MODEL)),
                ('member_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baptism_certificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baptism Record',
                'verbose_name_plural': 'Baptism Register',
                'ordering': ['-baptism_date'],
            },
        ),
    ]
