# Generated by Django 5.2.16 on 2026-07-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255, verbose_name="Child's Full Name")),
                ('father_name', models.CharField(max_length=255, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=255, verbose_name="Mother's Name")),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone', models.CharField(max_length=20, verbose_name='Parent Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent Email Address')),
                ('dedication_date', models.DateField(verbose_name='Date of Dedication')),
                ('officiating_pastor', models.CharField(max_length=255, verbose_name='Officiating Pastor')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Certificate Ready', 'Certificate Ready'), ('Pending Collection', 'Pending Collection'), ('Certificate Collected', 'Certificate Collected')], default='Processing', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Child Dedication',
                'verbose_name_plural': 'Child Dedications',
                'ordering': ['-dedication_date', '-created_at'],
            },
        ),
    ]
