# Generated by Django 5.2.16 on 2026-07-26 07:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_childdedication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('leader', models.CharField(max_length=255)),
                ('council_members', models.JSONField(blank=True, default=list)),
                ('tor_doc', models.FileField(blank=True, null=True, upload_to=core.models.upload_tor_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Monthly Report', 'Monthly Report'), ('Quarterly Report', 'Quarterly Report'), ('Event Report', 'Event Report')], max_length=50)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('report_file', models.FileField(upload_to=core.models.upload_report_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.department')),
            ],
            options={
                'ordering': ['-date', '-uploaded_at'],
            },
        ),
    ]
