# Generated by Django 5.2.16 on 2026-07-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_departmentalreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabbath_date', models.DateField(help_text='The Sabbath date for this bulletin')),
                ('title', models.CharField(blank=True, help_text='Optional custom title (e.g. Sabbath Bulletin - July 25, 2026)', max_length=255)),
                ('file', models.FileField(help_text='Upload Bulletin PDF document', upload_to='bulletins/%Y/%m/')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_bulletins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sabbath Bulletin',
                'verbose_name_plural': 'Sabbath Bulletins',
                'ordering': ['-sabbath_date'],
            },
        ),
    ]
