# Generated by Django 5.2.16 on 2026-07-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_ref', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Board Meetings', 'Board Meetings'), ('Business Meetings', 'Business Meetings'), ('Membership Reviews', 'Membership Reviews'), ('Delegate Related Meetings', 'Delegate Related Meetings'), ('Election Process Meetings', 'Election Process Meetings'), ('Committee Reporting Meetings', 'Committee Reporting Meetings')], default='Board Meetings', max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('chairperson', models.CharField(max_length=255)),
                ('pastor', models.CharField(max_length=255)),
                ('clerk', models.CharField(max_length=255)),
                ('agenda_doc', models.FileField(blank=True, null=True, upload_to='meetings/agendas/')),
                ('minutes_doc', models.FileField(blank=True, null=True, upload_to='meetings/minutes/')),
                ('physical_sheet', models.FileField(blank=True, null=True, upload_to='meetings/sheets/')),
                ('status', models.CharField(choices=[('Pending Minutes', 'Pending Minutes'), ('Minutes Confirmed', 'Minutes Confirmed')], default='Pending Minutes', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSheetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='meetings/attendance_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_sheets', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceApology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='meetings/apologies/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apologies', to='core.department')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apologies', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PR', 'Present'), ('AA', 'Absent with Apology'), ('WA', 'Absent without Apology')], default='PR', max_length=2)),
                ('arrival_time', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attendances', to='core.department')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.meeting')),
            ],
            options={
                'unique_together': {('meeting', 'member_name')},
            },
        ),
    ]
