# Generated by Django 5.2.16 on 2026-07-26 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_departmentrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('citizenship', models.CharField(default='Kenyan', max_length=100)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('joining_method', models.CharField(choices=[('Baptism', 'Baptism'), ('Transfer', 'Transfer'), ('Profession of Faith', 'Profession of Faith')], default='Baptism', max_length=30)),
                ('home_church', models.CharField(default='Newlife SDA Church', max_length=255)),
                ('year_joined', models.IntegerField(db_index=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('former_faith', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_church_letter', models.FileField(blank=True, null=True, upload_to='letters/previous_church/')),
                ('parents_consent_letter', models.FileField(blank=True, null=True, upload_to='letters/parents/')),
                ('baptism_card', models.FileField(blank=True, null=True, upload_to='cards/baptism/')),
                ('transfer_status', models.CharField(blank=True, choices=[('Request Made', 'Request Made'), ('Board Approval', 'Board Approval'), ('1st Reading', '1st Reading'), ('2nd Reading / Transfer Granted', '2nd Reading / Transfer Granted')], default='Request Made', max_length=50, null=True)),
                ('transfer_type', models.CharField(blank=True, choices=[('Transfer In', 'Transfer In'), ('Transfer Out', 'Transfer Out')], default='Transfer In', max_length=20, null=True)),
                ('origin_church', models.CharField(blank=True, max_length=255, null=True)),
                ('target_church', models.CharField(blank=True, max_length=255, null=True)),
                ('board_meeting_date', models.DateField(blank=True, null=True)),
                ('approval_minute', models.CharField(blank=True, max_length=100, null=True)),
                ('first_reading_date', models.DateField(blank=True, null=True)),
                ('second_reading_date', models.DateField(blank=True, null=True)),
                ('cbm_minute', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['year_joined', 'joining_method'], name='core_member_year_jo_0259ed_idx'), models.Index(fields=['full_name', 'phone_number'], name='core_member_full_na_52110a_idx')],
            },
        ),
    ]
