# Generated by Django 5.2.16 on 2026-07-27 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_memberrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_membership', models.CharField(default='NEWLIFE SDA CHURCH, 5TH AVENUE', max_length=255)),
                ('applicant_dob', models.DateField(blank=True, null=True)),
                ('applicant_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('applicant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_signature_date', models.DateField(blank=True, null=True)),
                ('spouse_name', models.CharField(max_length=255)),
                ('spouse_church', models.CharField(max_length=255)),
                ('spouse_conference', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_membership_no', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('spouse_dob', models.DateField(blank=True, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_phone', models.CharField(max_length=20)),
                ('spouse_address', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_signature_date', models.DateField(blank=True, null=True)),
                ('wedding_date', models.DateField()),
                ('wedding_place', models.CharField(default='NEWLIFE SDA CHURCH', max_length=255)),
                ('officiating_pastor', models.CharField(max_length=255)),
                ('counseling_pastor', models.CharField(blank=True, max_length=255, null=True)),
                ('officiating_elder', models.CharField(max_length=255)),
                ('reception_venue', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_received_date', models.DateField(blank=True, null=True)),
                ('groom_consent_file', models.FileField(blank=True, null=True, upload_to='wedding_docs/groom_consents/')),
                ('bride_consent_file', models.FileField(blank=True, null=True, upload_to='wedding_docs/bride_consents/')),
                ('recommendation_letter_file', models.FileField(blank=True, null=True, upload_to='wedding_docs/recommendations/')),
                ('has_applicant_parent_consent', models.BooleanField(default=False)),
                ('has_spouse_parent_consent', models.BooleanField(default=False)),
                ('has_recommendation_letter', models.BooleanField(default=False)),
                ('board_action_date', models.DateField(blank=True, null=True)),
                ('board_recommendations', models.TextField(blank=True, null=True)),
                ('board_chairman_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wedding Notification',
                'verbose_name_plural': 'Wedding Notifications',
                'ordering': ['-wedding_date'],
            },
        ),
    ]
