# Generated by Django 5.2.16 on 2026-07-28 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_weddingnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolyCommunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, default='2026', help_text='Year of the Holy Communion service (e.g. 2026)', max_length=4)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], db_index=True, default='Q1', help_text='Quarter of the church year', max_length=2)),
                ('service_date', models.DateField(help_text='Date on which the Holy Communion service was conducted')),
                ('members_present', models.PositiveIntegerField(help_text='Total number of members who partook in Holy Communion')),
                ('remarks', models.TextField(blank=True, help_text='Optional clerk notes or pastoral service remarks', null=True)),
                ('file', models.FileField(help_text='Scanned attendance roster / signed communion sheet (PDF/DOC)', upload_to='holy_communion_sheets/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Clerk who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holy Communion Record',
                'verbose_name_plural': 'Holy Communion Records',
                'ordering': ['-service_date'],
                'unique_together': {('year', 'quarter')},
            },
        ),
    ]
