# Generated by Django 5.2.16 on 2026-07-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_holycommunion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Board Meeting', 'Board Meeting'), ('Church Business Meeting', 'Church Business Meeting'), ('Baptism', 'Baptism'), ('Child Dedication', 'Child Dedication'), ('Wedding', 'Wedding'), ('Holy Communion', 'Holy Communion'), ('Camp Meeting', 'Camp Meeting'), ('Evangelism & Mission', 'Evangelism & Mission'), ('Departmental Event', 'Departmental Event'), ('General Fellowship', 'General Fellowship')], default='General Fellowship', max_length=50)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Members & Public'), ('BOARD', 'Church Board Only'), ('ELDERS', 'Elders Only'), ('LEADERS', 'Departmental Leaders Only'), ('CLERK_PASTOR', 'Clerk & Pastors Only')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('is_multi_day', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(default='Main Sanctuary', max_length=255)),
                ('organizer', models.CharField(default='Church Clerk Desk', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('groom_name', models.CharField(blank=True, default='', max_length=150)),
                ('bride_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
