# Generated by Django 5.2.16 on 2026-07-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leader_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ChurchWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(help_text='e.g. Senior Pastor, Head Elder, Choir Director', max_length=100)),
                ('worker_type', models.CharField(choices=[('PASTOR', 'Pastor'), ('ELDER', 'Elder'), ('CLERK', 'Church Clerk'), ('DEACON', 'Deacon / Deaconess'), ('DEPT_LEADER', 'Department Leader'), ('STAFF', 'Church Staff'), ('OTHER', 'Other Worker')], default='STAFF', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='core.department')),
            ],
            options={
                'verbose_name': 'Church Worker',
                'verbose_name_plural': 'Church Workers',
                'ordering': ['full_name'],
            },
        ),
    ]
